### ISSUE TITLE
如何判断 hmac 是 sha-1，sha-256 还是 sha-512 ？

### ISSUE THREAD

**Issue by Ferry-200** [MoyuScript/2fa-test#1]
在 [background](https://datatracker.ietf.org/doc/html/rfc6238#section-1.2) 中提到 totp 不一定像 hotp 那样使用 sha-1。不同的 hmac 会产生不同的验证码，该如何判断哪种是正确的？

Google Authentication 和 Microsoft Authentication 都可以兼容三种 hmac 的 totp，所以我觉得是有特定的判定方法的。

**Comment by MoyuScript** [comment]
https://github.com/google/google-authenticator/wiki/Key-Uri-Format

**Comment by Ferry-200** [comment]
👌。谢谢
